services:
  myproj-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myproj-webapi
    ports:
      - "7777:8080"
      - "443:443"  # HTTPS port qo'shilmoqda
    networks:
      - myproj-network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
     

networks:
  myproj-network:
    driver: bridge