version: '3.8'

services:
  myproj-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myproj-webapi
    ports:
      - "4040:8080"
      - "8081:8081"
    networks:
      - myproj-network
    restart: always    

networks:
  myproj-network:
    driver: bridge
